AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: mazy-video-tools-image-extractor

Parameters:
  VpcSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: VPC subnet IDs for Lambda functions
  VpcSecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: VPC security group IDs for Lambda functions

  ProgressQueueUrl:
    Type: String
    Description: URL da fila SQS para onde as mensagens de progresso e conclusão do job serão enviadas

  DatabaseHost:
    Type: String
    Description: Hostname ou endereço IP do seu cluster MongoDB

  DatabasePort:
    Type: String
    Description: Porta do seu cluster MongoDB

  DatabaseUser:
    Type: String
    Description: Usuário para autenticação no MongoDB

  DatabasePassword:
    Type: String
    Description: Senha para autenticação no MongoDB
    NoEcho: true

  DatabaseName:
    Type: String
    Description: Nome do banco de dados no MongoDB para persistência do job
    Default: mazy_video_tools_image_extractor

  CollectionName:
    Type: String
    Description: Nome da coleção no MongoDB para os documentos de job
    Default: video_jobs

Globals:
  Function:
    Timeout: 300
    MemorySize: 1024

Resources:
  InboundQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: mazy-video-tools-inbound
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt InboundDeadLetterQueue.Arn
        maxReceiveCount: 5

  FramesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mazy-video-tools-frames-e3b0245

  ZipBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mazy-video-tools-zip-e3b3245
      
  InboundDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: mazy-video-tools-inbound-dlq
      MessageRetentionPeriod: 1209600

  FfmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ffmpeg-layer
      Description: Layer contendo o binário estático do FFMPEG
      ContentUri: ffmpeg-layer/
      CompatibleRuntimes:
      - dotnet8

  VideoExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mazy-video-tools-image-extractor
      Runtime: dotnet8
      Handler: ImageExtractor::ImageExtractor.Function::FunctionHandler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      VpcConfig:
        SubnetIds: !Ref VpcSubnets
        SecurityGroupIds: !Ref VpcSecurityGroups
      CodeUri: ImageExtractor/
      Layers:
      - !Ref FfmpegLayer
      Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          Effect: Allow
          Action:
          - s3:GetObject
          Resource: !Sub arn:aws:s3:::${S3Bucket}/*
      Events:
        VideoSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt InboundQueue.Arn
            BatchSize: 1
      Environment:
        Variables:
          FRAMES_BUCKET_NAME: !Ref FramesBucket
          ZIP_BUCKET_NAME: !Ref ZipBucket
          PROGRESS_QUEUE_URL: !Ref ProgressQueueUrl
          MONGO_DB_HOST: !Ref DatabaseHost
          MONGO_DB_PORT: !Ref DatabasePort
          MONGO_DB_USER: !Ref DatabaseUser
          MONGO_DB_PASSWORD: !Ref DatabasePassword
          DATABASE_NAME: !Ref DatabaseName
          COLLECTION_NAME: !Ref CollectionName

Outputs:
  QueueUrl:
    Description: URL da fila SQS de entrada
    Value: !Ref InboundQueue